name: Integration Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        CLIENT_ID: ${{secrets.CLIENT_ID}}
        CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
        SERVER_ADDRESS: "wss://test.deribit.com/ws/api/v2"
        JSON_RPC: "2.0"  
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName~Integration"
